apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.cluster }}
  project: {{ .Values.project }}
  source:
    chart: sealed-secrets
    helm:
      parameters:
      valueFiles:
      - values.yaml
    repoURL: https://bitnami-labs.github.io/sealed-secrets/
    targetRevision: 2.10.0
